var u="c58acb989d34def5439484f91bfc23ea1584914e27312eeac19d89ee18d00343",h=`._container_hg2oa_1 {
  width: 100%;
  height: 100%;
  border-radius: var(--br);
  box-shadow: var(--box-shadow);
  background: linear-gradient(var(--lg));
  background-size: var(--background-size);
  background-repeat: no-repeat;
}
`;(function(){if(globalThis.window&&!document.getElementById(u)){var o=document.createElement("style");o.id=u,o.textContent=h,document.head.appendChild(o)}})();var p={container:"_container_hg2oa_1"};import{ControlType as e}from"framer";import{motion as x}from"framer-motion";import{ControlType as a}from"framer";var d={x:{type:a.Number,displayStepper:!0,defaultValue:0},y:{type:a.Number,displayStepper:!0,defaultValue:0},blur:{type:a.Number,displayStepper:!0,defaultValue:20},color:{type:a.Color,defaultValue:"rgba(0,0,0,0.08)"},size:{type:a.Number,displayStepper:!0,defaultValue:0}};import{jsx as s,jsxs as g}from"react/jsx-runtime";var b="hsl(243 90% 47%), hsl(286 95% 54%),hsl(333 100% 62%)",C=({colorsText:o=b,borderRadius:i=20,size:n=300,angle:r=0,blur:l=0,animation:{duration:m=2,animateAngle:c=!1},shadow:t})=>{let y=o.split(","),f=t?[t.x,t.y,t.blur,t.size,t.color].join(","):"none";return g("div",{style:{position:"relative",width:"100%",height:"100%",overflow:"hidden"},children:[s(x.div,{transition:{duration:m,repeat:1/0},animate:{backgroundPositionY:["0%","100%","0%"],backgroundPositionX:["0%","100%","0%"],...c?{"--angle":[r,r+180,r]}:{}},style:{"--lg":`${r}deg, ${y}`,"--br":`${i}px`,"--background-size":n?`${n}% ${n}%`:"300% 300%","--angle":r||0,"--box-shadow":f},className:p.container}),!!l&&s("div",{style:{width:"100%",height:"100%",position:"absolute",top:0,left:0,backdropFilter:`blur(${l}px)`,borderRadius:`${i}px`}})]})},$={colorText:{title:"Colors",type:e.Color,defaultValue:b},size:{type:e.Number,min:100,max:1e3,default:300},blur:{type:e.Number,defaultValue:0,displaySteppr:!0},angle:{type:e.Number,defaultValue:30,min:0,max:360,step:5},borderRadius:{type:e.Number,min:0,max:1e3},animation:{title:"Animation",type:e.Object,animateAngle:{type:e.Boolean,defaultValue:!1},duration:{title:"Duration",type:e.Number,defaultValue:10,displayStepper:!0}},applyBlur:{type:e.Boolean,defaultValue:!0},withShadow:{title:"With Shadow",type:e.Boolean,defaultValue:!1},shadow:{title:"Shadow",type:e.Object,controls:{...d}}};export{C as GradientBgAnimation,$ as propControls};
