export const components = {
  AutoGrid: {
    url: 'https://framer.com/m/AutoGrid-lTk2.js@hv170vfHp56WiPDicOIN',
    tags: ['Layout'],
    title: 'Auto Grid',
    createdAt: '2023-05-17',
    id: 1,
  },
  BlinkReveal: {
    url: 'https://framer.com/m/BlinkReveal-Z1Kr.js@SYPVg7J7tdzmb7tBMQc4',
    tags: ['Auto Animate'],
    title: 'Blink Reveal',
    createdAt: '2023-05-17',
    id: 2,
  },
  CircleCursor: {
    title: 'Circle Cursor',
    tags: ['Cursor'],
    url: 'https://framer.com/m/CircleCursor-TZIC.js@rXOZxpqFc89DgoF3W3zJ',
    createdAt: '2023-05-17',
    id: 3,
  },
  CopyText: {
    title: 'Copy Text',
    createdAt: '2023-05-17',
    id: 4,
    tags: ['Utility'],
    url: 'https://framer.com/m/CopyText-TgVP.js@qMjPPV1hBpxiqOCDmBER',
  },
  CustomCursorOnHover: {
    title: 'Custom Cursor On Hover',
    createdAt: '2023-05-17',
    id: 5,
    tags: ['Custom Cursor'],
    url: 'https://framer.com/m/CustomCursor-pqPs.js@ZBEe9yXyAPqqASoc9OQ2',
  },
  Donut: {
    title: 'Donut',
    createdAt: '2023-05-17',
    id: 6,
    tags: ['Utility'],
    url: 'https://framer.com/m/Donut-ZefS.js@OiMJhPX0OrV7CNaMx9lV',
  },
  Filters: {
    title: 'Filters',
    createdAt: '2023-05-17',
    id: 7,
    tags: ['Custom Effecs'],
    url: 'https://framer.com/m/Filters-gYW9.js@GhOMVTkTgPNOCCWNvJ5r',
  },
  FilpOnScroll: {
    title: 'Flip On Scroll (1)',
    createdAt: '2023-05-17',
    id: 8,
    tags: ['Auto Animate'],
    url: 'https://framer.com/m/FlipOnScroll-I5FG.js@VACmzoxNrqKpuO9SUwvm',
  },
  FilpOnScroll1: {
    title: 'Flip On Scroll (2)',
    createdAt: '2023-05-17',
    id: 9,
    tags: ['Auto Animate'],
    url: 'https://framer.com/m/FlipOnScroll2-FQjD.js@63KCJezVZt683mhhv04s',
  },
  FilpOnScroll2: {
    title: 'Flip On Scroll (3)',
    createdAt: '2023-05-17',
    id: 10,
    tags: ['Auto Animate'],
    url: 'https://framer.com/m/FlipOnScroll3-HDur.js@CGz3nyATFj4AfsEbAH36',
  },
  FollowCursor: {
    title: 'Follow Cursor',
    createdAt: '2023-05-17',
    id: 11,
    tags: ['Auto Animate'],
    url: 'https://framer.com/m/FollowCursor-8VZ4.js@hwMe09vSrYt9v4FVgAs1',
  },
  Goo: {
    title: 'Goo',
    createdAt: '2023-05-17',
    id: 12,
    tags: ['Turn Any Frame To Goo'],
    url: 'https://framer.com/m/Goo-aDY9.js@BMh3iTQQA3l7mvdYNEl2',
  },
  GradientBgAnimation: {
    title: 'Gradient Background Animation',
    createdAt: '2023-05-17',
    id: 13,
    tags: ['Auto Animate'],
    url: 'https://framer.com/m/GradientAnimation-Z2QX.js@I7At6FjVgrspY3dhA9q2',
  },
  HorizontalScroll: {
    title: 'Horizontal Scroll',
    createdAt: '2023-05-17',
    id: 14,
    tags: ['Easy To Apply Scroll'],
    url: 'https://framer.com/m/HorizontalScroll-3kAY.js@1WzqWLcy7itUAOUDwjMY',
  },
  ImageParallaxOnScroll: {
    title: 'Image Parallax On Scroll',
    createdAt: '2023-05-17',
    id: 15,
    tags: ['Auto Animate'],
    url: 'https://framer.com/m/ImageParallaxOnScroll-zKSV.js@oMRMFtiW3JnpMl9lTqK8',
  },
  ImageRepeatOnHover: {
    title: 'Image Repeat On Hover',
    createdAt: '2023-05-17',
    id: 16,
    tags: ['Auto Animate'],
    url: 'https://framer.com/m/ImageRepeatOnHover-i4km.js@GSklOxFSDxcrKXZjQX2y',
  },
  ImageScaleOnHover: {
    title: 'Image Scale On Hover',
    createdAt: '2023-05-17',
    id: 17,
    tags: ['Auto Animate'],
    url: 'https://framer.com/m/ImageScaleOnHover-OyFE.js@G7aOdRPmhJxnRNe7om9G',
  },
  ImageScaleOnScroll: {
    title: 'Image Scale On Scroll',
    createdAt: '2023-05-17',
    id: 18,
    tags: ['Auto Animate'],
    url: 'https://framer.com/m/ImageScaleOnScroll-fDFv.js@gTkZ5gyNbdpuaNWfDKFA',
  },
  LiquidReveal: {
    title: 'Liquid Reveal',
    createdAt: '2023-05-17',
    id: 19,
    tags: ['Animation Filter'],
    url: 'https://framer.com/m/LiquidReveal-mTqU.js@ycVQOJsmFqOuFnb8czwN',
  },
  MagneticButton: {
    title: 'Magnetic Button',
    createdAt: '2023-05-17',
    id: 20,
    tags: ['Auto Animate'],
    url: 'https://framer.com/m/MagneticButton-zZGS.js@eg47E9JkAY6MnPRzlYeS',
  },
  ScrollSnap: {
    title: 'Scroll Snap',
    createdAt: '2023-05-17',
    id: 21,
    tags: ['Utility'],
    url: 'https://framer.com/m/ScrollSnap-Iem8.js@HxexDtkkKnBFbVWW92W9',
  },
  ShuffleText: {
    title: 'Shuffle Text',
    createdAt: '2023-05-17',
    id: 22,
    tags: ['Text Animation'],
    url: 'https://framer.com/m/ShuffleText-r4I7.js@XxiRav85ztYQXkluHL5v',
  },
  SkewOnScroll: {
    title: 'Skew On Scroll',
    createdAt: '2023-05-17',
    id: 23,
    tags: ['Auto Animate'],
    url: 'https://framer.com/m/SkewOnScroll-DJxw.js@LhmpmdtQ1xBaDXMxHrqo',
  },
  Sparkles: {
    title: 'Sparkles',
    createdAt: '2023-05-17',
    id: 24,
    tags: ['Delightful Animation'],
    url: 'https://framer.com/m/Sparkles-27hx.js@hJK6jEQvXRUxcMddlsUx',
  },
  SplitTextReveal: {
    title: 'Split Text Reveal',
    createdAt: '2023-05-17',
    id: 25,
    tags: ['Text Animation'],
    url: 'https://framer.com/m/SplitTextReveal-z50F.js@bctO2c8ZeCQxYEfjDZO1',
  },
  Squircle: {
    title: 'Squircle',
    createdAt: '2023-05-17',
    id: 26,
    tags: ['Utility'],
    url: 'https://framer.com/m/Squircle-p7bb.js@GaIvjhkFMzr6Gciq7nvD',
  },
  TextRepeatOnScroll: {
    title: 'Text Repeat On Scroll',
    createdAt: '2023-05-17',
    id: 27,
    tags: ['Text Animation'],
    url: 'https://framer.com/m/TextRepeatOnScroll-XJsM.js@9Zq6yS9dNFMcHAfvnqaf',
  },
  TextRoll: {
    title: 'Text Roll',
    createdAt: '2023-05-17',
    id: 28,
    tags: [],
    url: 'https://framer.com/m/TextRoll-Oxux.js@LWWqM4X4bA2CDsiHC3Vo',
  },
  TextSlideInOnView: {
    title: 'Slide In On View',
    createdAt: '2023-05-17',
    id: 29,
    tags: [],
    url: 'https://framer.com/m/TextSlideInOnView-Pze7.js@HixC17QwBYMppbpnjnSn',
  },
  Typewriter: {
    title: 'Typewriter',
    createdAt: '2023-05-17',
    id: 30,
    tags: [],
    url: 'https://framer.com/m/Typewriter-mDTx.js@orzeSxQBhqeduyUB2R3n',
  },
  VideoPeek: {
    title: 'Video Peek',
    createdAt: '2023-05-17',
    id: 31,
    tags: [],
    url: 'https://framer.com/m/VideoPeek-PEf9.js@Jdz1bOYWuQ2WSKm222Xl',
  },
}
